# Generated by Django 2.1.3 on 2018-11-13 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=24)),
                ('street_direction', models.CharField(blank=True, max_length=4)),
                ('street_type', models.CharField(max_length=6)),
                ('secondary_address_line', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(max_length=24)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.BigIntegerField()),
                ('legal_acres', models.DecimalField(decimal_places=3, max_digits=6)),
                ('legal_description', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=84)),
                ('date_sold', models.DateField()),
                ('date_of_LLC_name_change', models.DateField()),
                ('date_of_mortgage', models.DateField()),
                ('mortgage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_class', models.CharField(max_length=3)),
                ('land_use', models.CharField(max_length=3)),
                ('tax_district', models.CharField(max_length=42)),
                ('school_district', models.CharField(max_length=42)),
                ('tax_lien', models.BooleanField()),
                ('cauv_property', models.BooleanField()),
                ('rental_registration', models.BooleanField()),
                ('current_market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year_2017_taxes', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAddress',
            fields=[
                ('addressproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propertyrecords.AddressProperties')),
                ('name', models.CharField(blank=True, max_length=24)),
            ],
            bases=('propertyrecords.addressproperties',),
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('addressproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='propertyrecords.AddressProperties')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='propertyrecords.Property')),
            ],
            bases=('propertyrecords.addressproperties',),
        ),
        migrations.CreateModel(
            name='TaxAddress',
            fields=[
                ('addressproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propertyrecords.AddressProperties')),
                ('name', models.CharField(blank=True, max_length=24)),
            ],
            bases=('propertyrecords.addressproperties',),
        ),
        migrations.AddField(
            model_name='addressproperties',
            name='owner_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.OwnerAddress'),
        ),
        migrations.AddField(
            model_name='addressproperties',
            name='tax_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.TaxAddress'),
        ),
    ]
