# Generated by Django 2.1.3 on 2018-11-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):


    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=24)),
                ('street_direction', models.CharField(blank=True, max_length=4)),
                ('street_type', models.CharField(max_length=6)),
                ('secondary_address_line', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(max_length=24)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.BigIntegerField()),
                ('legal_acres', models.DecimalField(decimal_places=3, max_digits=6)),
                ('legal_description', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=84)),
                ('date_sold', models.DateField()),
                ('date_of_LLC_name_change', models.DateField()),
                ('date_of_mortgage', models.DateField()),
                ('mortgage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_class', models.CharField(max_length=3)),
                ('land_use', models.CharField(max_length=3)),
                ('tax_district', models.CharField(max_length=42)),
                ('school_district', models.CharField(max_length=42)),
                ('tax_lien', models.BooleanField()),
                ('cauv_property', models.BooleanField()),
                ('rental_registration', models.BooleanField()),
                ('current_market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year_2017_taxes', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('addressproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='propertyrecords.AddressProperties')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='propertyrecords.Property')),
            ],
            options={
                'verbose_name_plural': 'property addresses',
            },
            bases=('propertyrecords.addressproperties',),
        ),
        migrations.CreateModel(
            name='TaxAddress',
            fields=[
                ('addressproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propertyrecords.AddressProperties')),
                ('name', models.CharField(blank=True, max_length=62)),
                ('secondary_name', models.CharField(blank=True, max_length=72)),
            ],
            options={
                'verbose_name_plural': 'tax addresses',
            },
            bases=('propertyrecords.addressproperties',),
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='owner_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.OwnerAddress'),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.TaxAddress'),
        ),
        migrations.AlterModelOptions(
            name='addressproperties',
            options={'verbose_name_plural': 'address properties'},
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='secondary_address_line',
            field=models.CharField(blank=True, help_text='Apartment, Floor, Etc. ', max_length=16),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('parcel_system_url', models.CharField(max_length=82)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('primary_url', models.CharField(max_length=82)),
                ('parcel_download_url', models.CharField(default=123, max_length=82)),
                ('type_of_key', models.CharField(default=123, help_text='Indicate what type of key we search with; i.e. parcel id? account number?', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='database_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.DatabaseProgram'),
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'counties'},
        ),
        migrations.RemoveField(
            model_name='county',
            name='parcel_system_url',
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='street_direction',
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='street_type',
        ),
        migrations.AddField(
            model_name='addressproperties',
            name='primary_address_line',
            field=models.CharField(blank=True, max_length=72),
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='city',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='secondary_address_line',
            field=models.CharField(blank=True, help_text='Apartment, Floor, Etc. ', max_length=72),
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_class',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_use',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='property',
            name='school_district_name',
            field=models.CharField(blank=True, max_length=52),
        ),
        migrations.AlterField(
            model_name='property',
            name='school_district',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_of_LLC_name_change',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_of_mortgage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='cauv_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='legal_acres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='legal_description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='property',
            name='mortgage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.CharField(blank=True, max_length=84),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='property',
            old_name='rental_registration',
            new_name='owner_occupancy_indicated',
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_occupancy_indicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='school_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_district',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_lien',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='taxable_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_2017_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_occupancy_indicated',
            field=models.BooleanField(default=False, help_text='Checked if an owner received an owner occupancy tax credit or if owner occupancy has been indicated on the record.'),
        ),
        migrations.CreateModel(
            name='TaxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxes_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.Property')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='current_market_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='taxable_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='year_2017_taxes',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_address',
        ),
        migrations.AlterField(
            model_name='property',
            name='parcel_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.County'),
        ),
        migrations.AlterField(
            model_name='county',
            name='database_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.DatabaseProgram'),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_of_mortgage',
            field=models.DateField(blank=True, help_text='Mortgages on a property at or after the date of sale', null=True),
        ),
    ]
