# Generated by Django 2.1.3 on 2018-11-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_address_line', models.CharField(blank=True, max_length=72)),
                ('secondary_address_line', models.CharField(blank=True, help_text='Apartment, Floor, Etc. ', max_length=72)),
                ('city', models.CharField(blank=True, max_length=24)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'address properties',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, unique=True)),
            ],
            options={
                'verbose_name_plural': 'counties',
            },
        ),
        migrations.CreateModel(
            name='DatabaseProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('primary_url', models.CharField(max_length=82)),
                ('parcel_download_url', models.CharField(max_length=82)),
                ('type_of_key', models.CharField(help_text='Indicate what type of key we search with; i.e. parcel id? account number?', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.BigIntegerField(unique=True)),
                ('legal_acres', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('legal_description', models.CharField(blank=True, max_length=120)),
                ('owner', models.CharField(blank=True, max_length=84)),
                ('date_sold', models.DateField(blank=True, null=True)),
                ('date_of_LLC_name_change', models.DateField(blank=True, null=True)),
                ('date_of_mortgage', models.DateField(blank=True, help_text='Mortgages on a property at or after the date of sale', null=True)),
                ('mortgage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_class', models.IntegerField(blank=True, null=True)),
                ('land_use', models.IntegerField(blank=True, null=True)),
                ('tax_district', models.CharField(blank=True, max_length=42)),
                ('school_district_name', models.CharField(blank=True, max_length=52)),
                ('school_district', models.IntegerField(blank=True, null=True)),
                ('tax_lien', models.BooleanField(default=False)),
                ('cauv_property', models.BooleanField(default=False)),
                ('owner_occupancy_indicated', models.BooleanField(default=False, help_text='Checked if an owner received an owner occupancy tax credit or if owner occupancy has been indicated on the record.')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='TaxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxes_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('addressproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='propertyrecords.AddressProperties')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='propertyrecords.Property')),
            ],
            options={
                'verbose_name_plural': 'property addresses',
            },
            bases=('propertyrecords.addressproperties',),
        ),
        migrations.CreateModel(
            name='TaxAddress',
            fields=[
                ('addressproperties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propertyrecords.AddressProperties')),
                ('name', models.CharField(blank=True, max_length=62)),
                ('secondary_name', models.CharField(blank=True, max_length=72)),
            ],
            options={
                'verbose_name_plural': 'tax addresses',
            },
            bases=('propertyrecords.addressproperties',),
        ),
        migrations.AddField(
            model_name='taxdata',
            name='property_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.County'),
        ),
        migrations.AddField(
            model_name='county',
            name='database_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.DatabaseProgram'),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.TaxAddress'),
        ),
    ]
