# Generated by Django 2.1.3 on 2018-11-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='owner_address',
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='tax_address',
        ),
        migrations.AddField(
            model_name='property',
            name='owner_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.OwnerAddress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='tax_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.TaxAddress'),
            preserve_default=False,
        ),
    ]
