# Generated by Django 2.1.3 on 2018-11-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tax_lien_information_source',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
