# Generated by Django 2.1.3 on 2018-11-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0002_auto_20181113_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressproperties',
            options={'verbose_name_plural': 'address properties'},
        ),
        migrations.AlterModelOptions(
            name='owneraddress',
            options={'verbose_name_plural': 'owner addresses'},
        ),
        migrations.AlterModelOptions(
            name='propertyaddress',
            options={'verbose_name_plural': 'property addresses'},
        ),
        migrations.AlterModelOptions(
            name='taxaddress',
            options={'verbose_name_plural': 'tax addresses'},
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='secondary_address_line',
            field=models.CharField(blank=True, help_text='Apartment, Floor, Etc. ', max_length=16),
        ),
    ]
