# Generated by Django 2.1.3 on 2018-11-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0002_property_tax_lien_information_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parcel_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
