# Generated by Django 2.1.3 on 2018-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0003_auto_20181127_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='account_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
