# Generated by Django 2.1.3 on 2018-11-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0003_auto_20181114_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('parcel_system_url', models.CharField(max_length=82)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('primary_url', models.CharField(max_length=82)),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='database_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.DatabaseProgram'),
        ),
    ]
