# Generated by Django 2.1.3 on 2018-11-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0004_auto_20181115_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'counties'},
        ),
    ]
