# Generated by Django 2.1.3 on 2018-12-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0004_property_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_sold',
            field=models.DateField(blank=True, help_text='Date a property sale was recorded. Might not have actually meant property sold for money, in the case of inheriting a property. ', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_class',
            field=models.CharField(blank=True, default='', max_length=48),
            preserve_default=False,
        ),
    ]
