# Generated by Django 2.1.3 on 2018-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0005_auto_20181201_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='account_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
