# Generated by Django 2.1.3 on 2018-11-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0005_auto_20181115_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='parcel_system_url',
        ),
        migrations.AddField(
            model_name='databaseprogram',
            name='parcel_download_url',
            field=models.CharField(default=123, max_length=82),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databaseprogram',
            name='type_of_key',
            field=models.CharField(default=123, help_text='Indicate what type of key we search with; i.e. parcel id? account number?', max_length=12),
            preserve_default=False,
        ),
    ]
