# Generated by Django 2.1.3 on 2018-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0006_auto_20181115_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressproperties',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='addressproperties',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=22, null=True),
        ),
    ]
