# Generated by Django 2.1.3 on 2018-11-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0007_auto_20181117_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressproperties',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='longitude',
        ),
    ]
