# Generated by Django 2.1.3 on 2018-12-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0007_auto_20181204_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressproperties',
            name='zipcode',
            field=models.CharField(blank=True, default=0, max_length=11),
            preserve_default=False,
        ),
    ]
