# Generated by Django 2.1.3 on 2018-11-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0008_auto_20181117_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressproperties',
            name='street_direction',
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='addressproperties',
            name='street_type',
        ),
        migrations.AddField(
            model_name='addressproperties',
            name='primary_address_line',
            field=models.CharField(blank=True, max_length=72),
        ),
        migrations.AddField(
            model_name='taxaddress',
            name='secondary_name',
            field=models.CharField(blank=True, max_length=72),
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='city',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='secondary_address_line',
            field=models.CharField(blank=True, help_text='Apartment, Floor, Etc. ', max_length=72),
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='addressproperties',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
