# Generated by Django 2.1.3 on 2018-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0008_auto_20181205_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_rating',
            field=models.CharField(blank=True, help_text='Property class rating, eg: A, B, C or D', max_length=2),
        ),
    ]
