# Generated by Django 2.1.3 on 2018-11-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0009_auto_20181118_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxaddress',
            name='name',
            field=models.CharField(blank=True, max_length=62),
        ),
    ]
