# Generated by Django 2.1.3 on 2018-11-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0010_auto_20181119_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tax_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.TaxAddress'),
        ),
    ]
