# Generated by Django 2.1.3 on 2018-12-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0010_propertytransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='legal_description',
            field=models.CharField(blank=True, max_length=230),
        ),
    ]
