# Generated by Django 2.1.3 on 2018-11-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0011_auto_20181119_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_class',
            field=models.IntegerField(),
        ),
    ]
