# Generated by Django 2.1.3 on 2018-11-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0013_auto_20181119_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='school_district_name',
            field=models.CharField(default='', max_length=52),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='school_district',
            field=models.IntegerField(),
        ),
    ]
