# Generated by Django 2.1.5 on 2019-01-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0013_lastscraped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastscraped',
            name='associated_county',
        ),
        migrations.AddField(
            model_name='property',
            name='last_scraped_one',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LastScraped',
        ),
    ]
