# Generated by Django 2.1.3 on 2018-11-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0014_auto_20181120_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_of_LLC_name_change',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_of_mortgage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
    ]
