# Generated by Django 2.1.5 on 2019-01-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0014_auto_20190117_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='tax_lien',
            new_name='tax_delinquent',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='tax_lien_information_source',
            new_name='tax_delinquent_year',
        ),
    ]
