# Generated by Django 2.1.3 on 2018-11-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0015_auto_20181121_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cauv_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='current_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='legal_acres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='legal_description',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='property',
            name='mortgage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.CharField(blank=True, max_length=84),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.OwnerAddress'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='school_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='school_district_name',
            field=models.CharField(blank=True, max_length=52),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_district',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_lien',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='taxable_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_2017_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
