# Generated by Django 2.1.5 on 2019-01-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0015_auto_20190119_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tax_delinquent_year',
        ),
    ]
