# Generated by Django 2.1.3 on 2018-11-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0016_auto_20181121_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='rental_registration',
            new_name='owner_occupancy_indicated',
        ),
    ]
