# Generated by Django 2.1.5 on 2019-02-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0017_property_tax_delinquent_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_of_mortgage',
            field=models.DateField(blank=True, help_text='Mortgages on a property at or after the date of sale', null=True, verbose_name='Estimated Market Value'),
        ),
    ]
