# Generated by Django 2.1.3 on 2018-11-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0017_auto_20181121_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner_occupancy_indicated',
            field=models.BooleanField(default=False, help_text='Checked if an owner received an owner occupancy tax credit or if owner occupancy has been indicated on the record.'),
        ),
    ]
