# Generated by Django 2.1.3 on 2018-11-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0018_auto_20181121_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taxes_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.Property')),
            ],
        ),
    ]
