# Generated by Django 2.1.7 on 2019-03-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0019_auto_20190202_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
