# Generated by Django 2.1.3 on 2018-11-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0020_auto_20181121_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owneraddress',
            name='addressproperties_ptr',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_address',
        ),
        migrations.DeleteModel(
            name='OwnerAddress',
        ),
    ]
