# Generated by Django 2.1.7 on 2019-03-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0021_property_tax_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rental_registration',
            field=models.BooleanField(default=False),
        ),
    ]
