# Generated by Django 2.1.3 on 2018-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0021_auto_20181121_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parcel_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
