# Generated by Django 2.1.3 on 2018-11-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0022_auto_20181122_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.County'),
        ),
        migrations.AlterField(
            model_name='county',
            name='database_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyrecords.DatabaseProgram'),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
