# Generated by Django 2.1.7 on 2019-03-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0022_property_rental_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytransfer',
            name='conveyance_number',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
