# Generated by Django 2.1.7 on 2019-03-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0023_auto_20190331_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytransfer',
            name='conveyance_number',
            field=models.CharField(blank=True, default='', max_length=35),
            preserve_default=False,
        ),
    ]
