# Generated by Django 2.1.3 on 2018-11-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0023_auto_20181124_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_of_mortgage',
            field=models.DateField(blank=True, help_text='Mortgages on a property at or after the date of sale', null=True),
        ),
    ]
