# Generated by Django 2.1.7 on 2019-04-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0024_auto_20190331_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytransfer',
            name='guarantee',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertytransfer',
            name='guarantor',
            field=models.CharField(max_length=200),
        ),
    ]
