# Generated by Django 2.1.7 on 2019-07-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0026_auto_20190617_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='last_scraped_two',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
