# Generated by Django 2.2.3 on 2019-07-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0027_property_last_scraped_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='parcel_number',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
