# Generated by Django 2.2.3 on 2019-07-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0028_auto_20190709_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressproperties',
            name='city',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
