# Generated by Django 2.2.3 on 2019-07-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyrecords', '0029_auto_20190721_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytransfer',
            name='guarantee',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='propertytransfer',
            name='guarantor',
            field=models.CharField(max_length=350),
        ),
    ]
